title: Portfolio
remote_theme: "jekyll/minima@1e8a445"

# Navigation
header_pages: []

# Social links (these will appear in the footer)
social:
  name: Sameer Anees Jaliawala
  links:
    - https://github.com/sameeranees
    - https://linkedin.com/in/sameer-anees
    - mailto:sameeraneesj@gmail.com

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
